### ISSUE TITLE
为什么不直接反序列化为C结构体（Why not deserialize directly to a C struct）

### ISSUE THREAD

**Issue by august295** [hardxuyp/PbConvertor#2]
我尝试直接反序列化为结构体，本人代码实现（I try to directly deserialize it into a struct, which is implemented by my code）
```cpp
bool PbConvertor::pb2struct(const google::protobuf::Message* pPb, char*& stru)
{
    if (NULL == pPb)
        return false;

    const google::protobuf::Descriptor* pDescriptor = pPb->GetDescriptor();
    if (NULL == pDescriptor)
        return false;
    const google::protobuf::Reflection* pReflection = pPb->GetReflection();
    if (NULL == pReflection)
        return false;

    for (size_t i = 0; i < pDescriptor->field_count(); ++i)
    {
        const google::protobuf::FieldDescriptor* pFieldDescriptor = pDescriptor->field(i);
        if (NULL == pFieldDescriptor)
            return false;

        switch (pFieldDescriptor->cpp_type())
        {
#define _CONVERT(type, pbType, getMethod, getRepeatedMethod)                                              \
    case google::protobuf::FieldDescriptor::pbType:                                                       \
    {                                                                                                     \
        if (pFieldDescriptor->is_repeated())                                                              \
        {                                                                                                 \
            if (i > 0)                                                                                    \
            {                                                                                             \
                size_t size;                                                                              \
                if (getSize(pReflection, pPb, pDescriptor->field(i - 1), size))                           \
                {                                                                                         \
                    if (size > 0)                                                                         \
                    {                                                                                     \
                        for (size_t j = 0; j < size; ++j)                                                 \
                            ((type*)stru)[j] = pReflection->getRepeatedMethod(*pPb, pFieldDescriptor, j); \
                    }                                                                                     \
                }                                                                                         \
            }                                                                                             \
            stru += sizeof(type*);                                                                        \
        }                                                                                                 \
        else                                                                                              \
        {                                                                                                 \
            *(type*)stru = pReflection->getMethod(*pPb, pFieldDescriptor);                                \
            stru += sizeof(type);                                                                         \
        }                                                                                                 \
        break;                                                                                            \
    }

            _CONVERT(double, CPPTYPE_DOUBLE, GetDouble, GetRepeatedDouble)
            _CONVERT(float, CPPTYPE_FLOAT, GetFloat, GetRepeatedFloat)
            _CONVERT(int32_t, CPPTYPE_INT32, GetInt32, GetRepeatedInt32)
            _CONVERT(int64_t, CPPTYPE_INT64, GetInt64, GetRepeatedInt64)
            _CONVERT(uint32_t, CPPTYPE_UINT32, GetUInt32, GetRepeatedUInt32)
            _CONVERT(uint64_t, CPPTYPE_UINT64, GetUInt64, GetRepeatedUInt64)
            _CONVERT(bool, CPPTYPE_BOOL, GetBool, GetRepeatedBool)
            _CONVERT(int, CPPTYPE_ENUM, GetEnumValue, GetRepeatedEnumValue)
#undef _CONVERT

        case google::protobuf::FieldDescriptor::CPPTYPE_STRING:
        {
            if (pFieldDescriptor->is_repeated())
            {
                if (i > 0)
                {
                    size_t size;
                    if (getSize(pReflection, pPb, pDescriptor->field(i - 1), size))
                    {
                        if (size > 0)
                        {
                            //*(char***)stru = (char**)calloc(size, sizeof(char*));
                            *(char***)stru = new char*[size * sizeof(char*)];
                            for (size_t j = 0; j < size; ++j)
                            {
                                std::string str;
                                str = pReflection->GetRepeatedStringReference(*pPb, pFieldDescriptor, j, &str);
                                size_t memSize2 = str.size() + 1;
                                //*(char**)stru = (char*)calloc(memSize2, sizeof(char));
                                *(char**)stru   = new char[memSize2 * sizeof(char)];
                                strcpy(*(char**)stru, str.c_str());
                            }
                        }
                    }
                }
                stru += sizeof(char*);
            }
            else
            {
                std::string str;
                str            = pReflection->GetStringReference(*pPb, pFieldDescriptor, &str);
                size_t memSize = str.size() + 1;
                //*(char**)stru = (char*)calloc(memSize, sizeof(char));
                *(char**)stru  = new char[memSize * sizeof(char)];
                strcpy(*(char**)stru, str.c_str());
                stru += sizeof(char*);
            }
            break;
        }

        case google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE:
        {
            if (pFieldDescriptor->is_repeated())
            {
                if (i > 0)
                {
                    size_t size;
                    if (getSize(pReflection, pPb, pDescriptor->field(i - 1), size))
                    {
                        if (size > 0)
                        {
                            //*(char**)stru = (char*)calloc(size, sizeof(char*));
                            *(char**)stru = new char[size * sizeof(char*)];
                            char* addr    = *(char**)stru;
                            for (size_t j = 0; j < size; ++j)
                            {
                                const google::protobuf::Message& childPb =
                                    pReflection->GetRepeatedMessage(*pPb, pFieldDescriptor, j);
                                if (!pb2struct(&childPb, addr))
                                    return false;
                            }
                        }
                    }
                }
                stru += sizeof(char*);
            }
            else
            {
                const google::protobuf::Message& childPb = pReflection->GetMessage(*pPb, pFieldDescriptor);
                if (!pb2struct(&childPb, *(char**)stru))
                    return false;
            }
            break;
        }

        default:
        {
            break;
        }
        }
    }
    return true;
}

bool PbConvertor::serializedPb2struct(const std::string& pbTypeName,
                                      const char*        pSerializedPb,
                                      const size_t       serializedPbSize,
                                      char*              stru)
{
    if (NULL == pSerializedPb)
        return false;

    const google::protobuf::Descriptor* pDescriptor =
        google::protobuf::DescriptorPool::generated_pool()->FindMessageTypeByName(pbTypeName);
    if (NULL == pDescriptor)
        return false;
    const google::protobuf::Message* pPrototype =
        google::protobuf::MessageFactory::generated_factory()->GetPrototype(pDescriptor);
    if (NULL == pPrototype)
        return false;
    google::protobuf::Message* pPb = pPrototype->New();
    if (NULL == pPb)
        return false;

    bool bRet = false;
    if (pPb->ParseFromArray(pSerializedPb, serializedPbSize))
        bRet = pb2struct(pPb, stru);
    delete pPb;
    return bRet;
}
```
使用代码， `AddressBook ` 是一个结构体（Using code, `addressbook 'is a structure）
```cpp
AddressBook stru;
ret = PbConvertor::serializedPb2struct("TEST.AddressBook", pSerializedPb, serializedPbSize, (char*)&stru);
```

但是有时候会内存溢出，并且不知道怎么删除分配制的内存，因为是直接 `char*` 自动对齐导致删除时出现 `Expression: _CrtisvalidHeapPointer(block)`，代码需要怎么修改？（However, sometimes the memory overflows, and I don't know how to delete the allocated memory, because the direct 'char *' automatic alignment causes the 'expression:_ Crtisvalidheppointer (block) `, how do I modify the code?）
![image](https://user-images.githubusercontent.com/45315371/174422088-5386b69b-7ce1-42f0-8eae-c89d7645e415.png)

请问作者能够实现反序列化结构体吗？（Can the author implement the deserialization structure?）

**Comment by hardxuyp** [comment]
仔细看readme和例子，你就不会遇到这些问题。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: august295 ***@***.***&gt;
发送时间: 2022年6月18日 12:11
收件人: hardxuyp/PbConvertor ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [hardxuyp/PbConvertor] 为什么不直接反序列化为C结构体（Why not deserialize directly to a C struct） (Issue #2)





 
我尝试直接反序列化为结构体，本人代码实现（I try to directly deserialize it into a struct, which is implemented by my code）
 bool PbConvertor::pb2struct(const google::protobuf::Message* pPb, char*&amp; stru) {     if (NULL == pPb)         return false;     const google::protobuf::Descriptor* pDescriptor = pPb-&gt;GetDescriptor();     if (NULL == pDescriptor)         return false;     const google::protobuf::Reflection* pReflection = pPb-&gt;GetReflection();     if (NULL == pReflection)         return false;     for (size_t i = 0; i < pDescriptor-&gt;field_count(); ++i)     {         const google::protobuf::FieldDescriptor* pFieldDescriptor = pDescriptor-&gt;field(i);         if (NULL == pFieldDescriptor)             return false;         switch (pFieldDescriptor-&gt;cpp_type())         { #define _CONVERT(type, pbType, getMethod, getRepeatedMethod)                                              \     case google::protobuf::FieldDescriptor::pbType:                                                       \     {                                                                                                     \         if (pFieldDescriptor-&gt;is_repeated())                                                              \         {                                                                                                 \             if (i &gt; 0)                                                                                    \             {                                                                                             \                 size_t size;                                                                              \                 if (getSize(pReflection, pPb, pDescriptor-&gt;field(i - 1), size))                           \                 {                                                                                         \                     if (size &gt; 0)                                                                         \                     {                                                                                     \                         for (size_t j = 0; j < size; ++j)                                                 \                             ((type*)stru)[j] = pReflection-&gt;getRepeatedMethod(*pPb, pFieldDescriptor, j); \                     }                                                                                     \                 }                                                                                         \             }                                                                                             \             stru += sizeof(type*);                                                                        \         }                                                                                                 \         else                                                                                              \         {                                                                                                 \             *(type*)stru = pReflection-&gt;getMethod(*pPb, pFieldDescriptor);                                \             stru += sizeof(type);                                                                         \         }                                                                                                 \         break;                                                                                            \     }             _CONVERT(double, CPPTYPE_DOUBLE, GetDouble, GetRepeatedDouble)             _CONVERT(float, CPPTYPE_FLOAT, GetFloat, GetRepeatedFloat)             _CONVERT(int32_t, CPPTYPE_INT32, GetInt32, GetRepeatedInt32)             _CONVERT(int64_t, CPPTYPE_INT64, GetInt64, GetRepeatedInt64)             _CONVERT(uint32_t, CPPTYPE_UINT32, GetUInt32, GetRepeatedUInt32)             _CONVERT(uint64_t, CPPTYPE_UINT64, GetUInt64, GetRepeatedUInt64)             _CONVERT(bool, CPPTYPE_BOOL, GetBool, GetRepeatedBool)             _CONVERT(int, CPPTYPE_ENUM, GetEnumValue, GetRepeatedEnumValue) #undef _CONVERT         case google::protobuf::FieldDescriptor::CPPTYPE_STRING:         {             if (pFieldDescriptor-&gt;is_repeated())             {                 if (i &gt; 0)                 {                     size_t size;                     if (getSize(pReflection, pPb, pDescriptor-&gt;field(i - 1), size))                     {                         if (size &gt; 0)                         {                             //*(char***)stru = (char**)calloc(size, sizeof(char*));                             *(char***)stru = new char*[size * sizeof(char*)];                             for (size_t j = 0; j < size; ++j)                             {                                 std::string str;                                 str = pReflection-&gt;GetRepeatedStringReference(*pPb, pFieldDescriptor, j, &amp;str);                                 size_t memSize2 = str.size() + 1;                                 //*(char**)stru = (char*)calloc(memSize2, sizeof(char));                                 *(char**)stru   = new char[memSize2 * sizeof(char)];                                 strcpy(*(char**)stru, str.c_str());                             }                         }                     }                 }                 stru += sizeof(char*);             }             else             {                 std::string str;                 str            = pReflection-&gt;GetStringReference(*pPb, pFieldDescriptor, &amp;str);                 size_t memSize = str.size() + 1;                 //*(char**)stru = (char*)calloc(memSize, sizeof(char));                 *(char**)stru  = new char[memSize * sizeof(char)];                 strcpy(*(char**)stru, str.c_str());                 stru += sizeof(char*);             }             break;         }         case google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE:         {             if (pFieldDescriptor-&gt;is_repeated())             {                 if (i &gt; 0)                 {                     size_t size;                     if (getSize(pReflection, pPb, pDescriptor-&gt;field(i - 1), size))                     {                         if (size &gt; 0)                         {                             //*(char**)stru = (char*)calloc(size, sizeof(char*));                             *(char**)stru = new char[size * sizeof(char*)];                             char* addr    = *(char**)stru;                             for (size_t j = 0; j < size; ++j)                             {                                 const google::protobuf::Message&amp; childPb =                                     pReflection-&gt;GetRepeatedMessage(*pPb, pFieldDescriptor, j);                                 if (!pb2struct(&amp;childPb, addr))                                     return false;                             }                         }                     }                 }                 stru += sizeof(char*);             }             else             {                 const google::protobuf::Message&amp; childPb = pReflection-&gt;GetMessage(*pPb, pFieldDescriptor);                 if (!pb2struct(&amp;childPb, *(char**)stru))                     return false;             }             break;         }         default:         {             break;         }         }     }     return true; } bool PbConvertor::serializedPb2struct(const std::string&amp; pbTypeName,                                       const char*        pSerializedPb,                                       const size_t       serializedPbSize,                                       char*              stru) {     if (NULL == pSerializedPb)         return false;     const google::protobuf::Descriptor* pDescriptor =         google::protobuf::DescriptorPool::generated_pool()-&gt;FindMessageTypeByName(pbTypeName);     if (NULL == pDescriptor)         return false;     const google::protobuf::Message* pPrototype =         google::protobuf::MessageFactory::generated_factory()-&gt;GetPrototype(pDescriptor);     if (NULL == pPrototype)         return false;     google::protobuf::Message* pPb = pPrototype-&gt;New();     if (NULL == pPb)         return false;     bool bRet = false;     if (pPb-&gt;ParseFromArray(pSerializedPb, serializedPbSize))         bRet = pb2struct(pPb, stru);     delete pPb;     return bRet; }
 
使用代码， AddressBook  是一个结构体（Using code, `addressbook 'is a structure）
 AddressBook stru; ret = PbConvertor::serializedPb2struct("TEST.AddressBook", pSerializedPb, serializedPbSize, (char*)&amp;stru);
 
但是有时候会内存溢出，并且不知道怎么删除分配制的内存，因为是直接 char* 自动对齐导致删除时出现 Expression: _CrtisvalidHeapPointer(block)，代码需要怎么修改？（However, sometimes the memory overflows, and I don't know how to delete the allocated memory, because the direct 'char *' automatic alignment causes the 'expression:_ Crtisvalidheppointer (block) `, how do I modify the code?）
 
 
请问作者能够实现反序列化结构体吗？（Can the author implement the deserialization structure?）

**Comment by august295** [comment]
问题解决了，我将 `PbConvertor::MemTree stru` 直接指针强转了，实际上是 `stru.pMem` 进行强转，没仔细看，十分感谢（The problem is solved. I forcibly rotate the 'pbconverter:: memtree stru' direct pointer, which is actually 'stru Pmem` did a forced conversion without looking carefully. Thank you very much）

**Comment by hardxuyp** [comment]
不客气，周末大中午还在搞技术，为你点赞。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: august295 ***@***.***&gt;
发送时间: 2022年6月18日 12:45
收件人: hardxuyp/PbConvertor ***@***.***&gt;
抄送: hardxuyp ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [hardxuyp/PbConvertor] 为什么不直接反序列化为C结构体（Why not deserialize directly to a C struct） (Issue #2)





 
问题解决了，我将 PbConvertor::MemTree stru 直接指针强转了，实际上是 stru.pMem 进行强转，没仔细看，十分感谢（The problem is solved. I forcibly rotate the 'pbconverter:: memtree stru' direct pointer, which is actually 'stru Pmem` did a forced conversion without looking carefully. Thank you very much）
